### ISSUE TITLE
Please could we publish this package to CRAN

### ISSUE THREAD

**Issue by xiying2014** [deepanshu88/summaryBox#1]
Hello Deepanshu,

This package is fantastic!!! It is exactly what I am looking for my project!!! Just wondering please could we publish it in CRAN. Therefore it will allow me to use this package in the organization instead of my personal PC. 

Many thank and look forward to your reply!

**Comment by PBMCHUGA** [comment]
Hi,

I love your boxes but still I don't find the package on CRAN. Is it available on R 4.2.1 ?

Thanks
