### ISSUE TITLE
openBinaryFile missing after updates

### ISSUE THREAD

**Issue by riskcede** [deepanshu88/summaryBox#4]
Thank you for this library, i like using it short rmd output.

Ive recently updated a lot of libraries and now im getting an error when i run the summaryBox() function:

pandoc: /home/jan/R/x86_64-pc-linux-gnu-library/4.1/fontawesome/fontawesome/css/../webfonts/fa-v4compatibility.woff2: openBinaryFile: does not exist (No such file or directory)
Error: pandoc document conversion failed with error 1

Please see system info below:

> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8      
 [8] LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] summaryBox_0.1.0

loaded via a namespace (and not attached):
 [1] compiler_4.1.0   fastmap_1.1.0    cli_3.4.1        htmltools_0.5.3  tools_4.1.0      rstudioapi_0.14  yaml_2.3.6       rmarkdown_2.18.1 knitr_1.41      
[10] xfun_0.35        digest_0.6.30    rlang_1.0.6      evaluate_0.18   

Can you please advise if there is something i need to install or download?

Regards
Jan

**Comment by Stephonomon** [comment]
Same. I tried running your test.rmd, and produced the same error.

R Version
--------------------------------------------------
platform       : x86_64-w64-mingw32
arch           : x86_64
os             : mingw32
crt            : ucrt
system         : x86_64, mingw32
status         : 
major          : 4
minor          : 2.2
year           : 2022
month          : 10
day            : 31
svn rev        : 83211
language       : R
version.string : R version 4.2.2 (2022-10-31 ucrt)
nickname       : Innocent and Trusting

System Information
--------------------------------------------------
sysname        : Windows     
release        : 10 x64      
version        : build 19042 

Loaded Packages
--------------------------------------------------
base           : C:/PROGRA~1/R/R-42~1.2/library/base                             
compiler       : C:/Program Files/R/R-4.2.2/library/compiler                     
datasets       : C:/Program Files/R/R-4.2.2/library/datasets                     
graphics       : C:/Program Files/R/R-4.2.2/library/graphics                     
grDevices      : C:/Program Files/R/R-4.2.2/library/grDevices                    
methods        : C:/Program Files/R/R-4.2.2/library/methods                      
stats          : C:/Program Files/R/R-4.2.2/library/stats                        
tools          : C:/Program Files/R/R-4.2.2/library/tools                        
utils          : C:/Program Files/R/R-4.2.2/library/utils                        
cli            : C:/Users/proctors/AppData/Local/R/win-library/4.2/cli           
digest         : C:/Users/proctors/AppData/Local/R/win-library/4.2/digest        
evaluate       : C:/Users/proctors/AppData/Local/R/win-library/4.2/evaluate      
fastmap        : C:/Users/proctors/AppData/Local/R/win-library/4.2/fastmap       
htmltools      : C:/Users/proctors/AppData/Local/R/win-library/4.2/htmltools     
htmlwidgets    : C:/Users/proctors/AppData/Local/R/win-library/4.2/htmlwidgets   
knitr          : C:/Users/proctors/AppData/Local/R/win-library/4.2/knitr         
later          : C:/Users/proctors/AppData/Local/R/win-library/4.2/later         
magrittr       : C:/Users/proctors/AppData/Local/R/win-library/4.2/magrittr      
promises       : C:/Users/proctors/AppData/Local/R/win-library/4.2/promises      
R6             : C:/Users/proctors/AppData/Local/R/win-library/4.2/R6            
Rcpp           : C:/Users/proctors/AppData/Local/R/win-library/4.2/Rcpp          
rlang          : C:/Users/proctors/AppData/Local/R/win-library/4.2/rlang         
rmarkdown      : C:/Users/proctors/AppData/Local/R/win-library/4.2/rmarkdown     
rpivotTable    : C:/Users/proctors/AppData/Local/R/win-library/4.2/rpivotTable   
rstudioapi     : C:/Users/proctors/AppData/Local/R/win-library/4.2/rstudioapi    
shinydashboard : C:/Users/proctors/AppData/Local/R/win-library/4.2/shinydashboard
xfun           : C:/Users/proctors/AppData/Local/R/win-library/4.2/xfun          
yaml           : C:/Users/proctors/AppData/Local/R/win-library/4.2/yaml

**Comment by deepanshu88** [comment]
This issue is related to rmarkdown. [https://github.com/rstudio/rmarkdown/issues/1632](rmarkdown)

**Comment by deepanshu88** [comment]
@Stephonomon  You are getting the error without loading `summaryBox` package as shown in your snapshot.

**Comment by riskcede** [comment]
Thanks for the feedback. Makes sense!Ill read up on that ticket thread… hope they solve it from the rmarkdown side so that I can start using the summary boxes in reports again.By any chance, are you aware of a workaround for this?On 28 Nov 2022, at 16:41, deepanshu88 ***@***.***> wrote:﻿
This issue is related to rmarkdown. https://github.com/rstudio/rmarkdown/issues/1632
